language: cpp
sudo: false
dist: bionic
compiler:
  - gcc
  - clang

install:

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++ CC=gcc
    - os: linux
      env: COMPILER_NAME=clang CXX=clang++ CC=clang

before_script:
  - cd ${TRAVIS_BUILD_DIR}/test/
  - mkdir build
  - cd build
  - cmake ..
script:
  - make
  - ./cppjson

